/*
Problem description:
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

page link:
https://projecteuler.net/problem=45

dax 2023-05-23 15:21:24
*/
#include "problem.h"
#include "number.h"

unsigned long Solution::find_next()
{
	unsigned n = 286;

	while(true)
	{
		unsigned long number = (n * n + n) / 2;

		if(is_pentagonal_number(number) && is_hexagonal_number(number)) return number;

		++n;
	}
}

void Solution::answer()
{
	std::cout << "The answer is: " << find_next() << std::endl;
}
