/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

dax 2023/04/20 14:54:59
*/

#include "problem.h"

std::vector<int> Solution::fibs(int cap)
{
	std::vector<int> fb;
	int a = 0, b = 1, c = 1;

	while(c <= cap)
	{
		fb.push_back(c);
		a = b;
		b = c;
		c = a + b;
	}

	return fb;
}

long Solution::sum_of_even_fibs(int cap)
{
	long sum{};
	std::vector<int> fb = fibs(cap);

	for(auto item : fb)
	{
		if(item % 2 == 0) sum += item;
	}

	return sum;
}
